apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: meme-web-backend
  description: meme-web backend service
  annotations:
    backstage.io/techdocs-ref: dir:.
    backstage.io/kubernetes-id: meme-web-backend
  tags:
    - nodejs
  links:
    - title: Documentation
      url: https://github.com/AATT_GITHUB_USERNAME/automate-all-the-things-unnamed
    - url: https://admin.example-org.com
      title: Admin Dashboard
      icon: dashboard
      type: admin-dashboard
    - url: https://grafana.domain.com/
      title: metrics
      icon: analytics
      type: metrics-dashboard
    - url: https://grafana.domain.com/
      title: logs
      icon: assignment
      type: logs-dashboard  
spec:
  type: service
  lifecycle: production
  owner: meme-web-backend-subteam
  system: meme-web
  dependsOn:
    - resource:default/meme-web-redis
  providesApis:
    - meme-web-backend-api
