apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: new-backstage-system
  title: New Backstage System
  description: Create new Backstage system
  tags:
    - backstage
spec:
  owner: web@example.com
  type: component
  parameters:
    - title: Provide some simple information
      required:
        - name
        - description
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Name of the new system
          ui:field: EntityNamePicker
          ui:autofocus: true
        description:
          title: Description
          type: string
          description: Help others understand what this system is for
        owner:
          title: Owner
          type: string
          description: Owner of the service
          ui:field: OwnerPicker
          ui:options:
            allowedKinds:
              - Group
        tags:
          title: Tags
          type: array
          items:
            type: string
          description: Tags associated with the system
          # ui:field: TagsPicker
          # ui:options:
          #   freeSolo: true  

    - title: Choose a location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          tags: ${{ parameters.tags }}

    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        allowedHosts: ['github.com']
        repoUrl: ${{ parameters.repoUrl }}
        title: "Create new system: ${{parameters.name}}"
        branchName: create-system-${{parameters.name | lower }}
        description: |
          # New system: ${{parameters.name}}

          ${{ parameters.description if parameters.description }}
        targetPath: backstage/entities/systems
        
  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        title: "Go to PR"

