appName: AATT_APP_NAME # This value was modified by the initial-setup python script

service: backend

port: 3000

deployment:
  labels: {    
    istio: monitor # This label is used by the PodMonitor
  }
  image:
    repository: AATT_DOCKERHUB_USERNAME/AATT_APP_NAME-backend # This value was modified by the harbor-setup pipeline